// <auto-generated />
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(CurseContext))]
    [Migration("20200811052641_CurseSeed")]
    partial class CurseSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Curse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Curses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Po šimts pypkių!"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Rupūs miltai!"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Kad tau grybai ausis užkištų!"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Kad tave šunys užmirštų"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Eik tu balų degint"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Po šimts gegučių!"
                        },
                        new
                        {
                            Id = 7,
                            Text = "Kad tave zuikis subadytų!"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Žalčio koja pastaroji!"
                        },
                        new
                        {
                            Id = 9,
                            Text = "Papūsk dyglei į rankovę!"
                        },
                        new
                        {
                            Id = 10,
                            Text = "Ot tu šuns pasturgali"
                        },
                        new
                        {
                            Id = 11,
                            Text = "Apsišik aukštielninkas"
                        },
                        new
                        {
                            Id = 12,
                            Text = "Šliaušk tarybiniais vamzdžiais"
                        },
                        new
                        {
                            Id = 13,
                            Text = "Įsikąsk į stuburą"
                        },
                        new
                        {
                            Id = 14,
                            Text = "Elniaragį tau į subinę"
                        },
                        new
                        {
                            Id = 15,
                            Text = "Eik tu kiaulėms uodegas mazgoti"
                        },
                        new
                        {
                            Id = 16,
                            Text = "Papūsk šuniui į uodegą!"
                        },
                        new
                        {
                            Id = 17,
                            Text = "Ko prikibai kaip lapas prie užpakalio!"
                        },
                        new
                        {
                            Id = 18,
                            Text = "O tu šuns kumpi"
                        },
                        new
                        {
                            Id = 19,
                            Text = "Kramtyk mėšlą"
                        },
                        new
                        {
                            Id = 20,
                            Text = "Surūgsi kaip kisielius!"
                        },
                        new
                        {
                            Id = 21,
                            Text = "Pakasyk sliekui pažastį!"
                        },
                        new
                        {
                            Id = 22,
                            Text = "Kad tave varnos sulestų!"
                        },
                        new
                        {
                            Id = 23,
                            Text = "Snarglių kompotas!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
